// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOY9YxFPoqJADMP0hfQX1tgAngODucpzI',
    appId: '1:953745730504:android:b7ac7d0d1a75dba20faefd',
    messagingSenderId: '953745730504',
    projectId: 'shopping-list-62922',
    databaseURL: 'https://shopping-list-62922-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-62922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvbWlCM_i39fl7mzB8g-dUTDbHSg7YGq4',
    appId: '1:953745730504:ios:dfe8639067cf467c0faefd',
    messagingSenderId: '953745730504',
    projectId: 'shopping-list-62922',
    databaseURL: 'https://shopping-list-62922-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-62922.firebasestorage.app',
    iosBundleId: 'com.example.shoppinglistapp',
  );
}
